# Generated by Django 4.2.5 on 2023-10-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTier',
            fields=[
                ('tier_number', models.AutoField(primary_key=True, serialize=False)),
                ('tier_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
