# Generated by Django 4.2.5 on 2023-10-04 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0003_grantedtier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantedtier',
            name='account_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.accounttier'),
        ),
        migrations.AlterField(
            model_name='grantedtier',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
