# Generated by Django 4.2.5 on 2023-10-04 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_tiergrantedprivilege'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringLinksGrantedPriviledges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiring_link', models.BooleanField(default=False)),
                ('account_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.accounttier')),
            ],
        ),
        migrations.CreateModel(
            name='LinkToOriginalGrantedPriviledges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_original_image', models.BooleanField(default=False)),
                ('account_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.accounttier')),
            ],
        ),
        migrations.CreateModel(
            name='ThumbnailGrantedPrivileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.accounttier')),
                ('thumbnail_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.thumbnailsize')),
            ],
        ),
        migrations.DeleteModel(
            name='TierGrantedPrivilege',
        ),
    ]
