# Generated by Django 4.2.5 on 2023-10-05 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_expiringlinksgrantedpriviledges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiringlink',
            name='url',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='LinkToOriginalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
            ],
        ),
    ]
