# Generated by Django 4.2.5 on 2023-10-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_expiringlink_url_alter_image_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpiringLinksGrantedPriviledges',
            new_name='ExpiringLinkGrantedPrivileges',
        ),
        migrations.RenameModel(
            old_name='LinkToOriginalGrantedPriviledges',
            new_name='LinkToOriginalGrantedPrivileges',
        ),
    ]
