# Generated by Django 4.2.5 on 2023-10-05 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0010_rename_expiringlinksgrantedpriviledges_expiringlinkgrantedprivileges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnailsize',
            name='base_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='images.image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_image', models.ImageField(upload_to='thumbnails/%Y/%m/%d/')),
                ('thumbnail_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
