# Generated by Django 4.2.5 on 2023-10-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_thumbnailsize_base_image_alter_image_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnailsize',
            name='base_image',
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail_size',
            field=models.PositiveIntegerField(choices=[('200px', 200)]),
        ),
    ]
