# Generated by Django 4.2.6 on 2023-10-06 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_remove_thumbnailsize_base_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiringlinkgrantedprivileges',
            name='seconds',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail_size',
            field=models.PositiveIntegerField(),
        ),
    ]
