# Generated by Django 4.2.6 on 2023-10-06 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_expiringlinkgrantedprivileges_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expiringlinkgrantedprivileges',
            name='seconds',
        ),
        migrations.AddField(
            model_name='expiringlink',
            name='seconds',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(30)]),
        ),
    ]
