# Generated by Django 4.2.6 on 2023-10-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_remove_expiringlink_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiringlink',
            name='base_image',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='images.image'),
            preserve_default=False,
        ),
    ]
