# Generated by Django 4.2.6 on 2023-10-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_expiringlink_base_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringlink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expiring/%Y/%m/%d/'),
        ),
    ]
