# Generated by Django 4.2.6 on 2023-10-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_alter_expiringlink_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkToOriginalImage',
        ),
    ]
