# Generated by Django 4.2.6 on 2023-10-07 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_delete_linktooriginalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringlink',
            name='image',
            field=models.ImageField(upload_to='expiring/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
